-- Functional index so lower(email) lookups (ensureAuthUser's deactivated-user
-- check, run on every sign-in) can use an index instead of a full table scan.
-- Not representable in schema.prisma (Prisma has no expression-index syntax),
-- so this migration is hand-written rather than generated by `prisma migrate dev`.
-- CreateIndex
CREATE INDEX "User_email_lower_idx" ON "User" (lower("email"));
